# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gotop-unstable-${version}";
  version = "2018-04-01";
  rev = "1a61eb2153453aced9e2c5a100c4b727f3b2aa00";

  goPackagePath = "github.com/cjbassi/gotop";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/cjbassi/gotop";
    sha256 = "0cyxhay03qw49rv5s9sxnv3dhwqkaj7hjgg6bbmv2hmhkh6qj140";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
