# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/cjbassi/termui";
    fetch = {
      type = "git";
      url = "https://github.com/cjbassi/termui";
      rev = "caeddf326ed4eb0a443f865b619d49baefd552fa";
      sha256 = "12vxqsl9llpj23cnf9msfscngbr87jclwvy89k7bb61av9jgsfk3";
    };
  }
]
