# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, fetchFromGitHub, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.0" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.0.tgz";
        sha1 = "d0554c2256636e2f56e7c2e5ad183f859428d81f";
      };
    };
    "ajv-4.11.8" = {
      name = "ajv";
      packageName = "ajv";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-4.11.8.tgz";
        sha1 = "82ffb02b29e662ae53bdc20af15947706739c536";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-term-0.0.2" = {
      name = "ansi-term";
      packageName = "ansi-term";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-term/-/ansi-term-0.0.2.tgz";
        sha1 = "fd753efa4beada0eac99981bc52a3f6ff019deb7";
      };
    };
    "ansicolors-0.2.1" = {
      name = "ansicolors";
      packageName = "ansicolors";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansicolors/-/ansicolors-0.2.1.tgz";
        sha1 = "be089599097b74a5c9c4a84a0cdbcdb62bd87aef";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "blessed-0.1.81" = {
      name = "blessed";
      packageName = "blessed";
      version = "0.1.81";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed/-/blessed-0.1.81.tgz";
        sha1 = "f962d687ec2c369570ae71af843256e6d0ca1129";
      };
    };
    "blessed-contrib-4.7.5" = {
      name = "blessed-contrib";
      packageName = "blessed-contrib";
      version = "4.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed-contrib/-/blessed-contrib-4.7.5.tgz";
        sha1 = "4fae074bbdc0a3af59671fcf54361e9c011576b3";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "bresenham-0.0.3" = {
      name = "bresenham";
      packageName = "bresenham";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bresenham/-/bresenham-0.0.3.tgz";
        sha1 = "abdab9e5b194e27c757cd314d8444314f299877a";
      };
    };
    "buffers-0.1.1" = {
      name = "buffers";
      packageName = "buffers";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz";
        sha1 = "b24579c3bed4d6d396aeee6d9a8ae7f5482ab7bb";
      };
    };
    "cardinal-1.0.0" = {
      name = "cardinal";
      packageName = "cardinal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cardinal/-/cardinal-1.0.0.tgz";
        sha1 = "50e21c1b0aa37729f9377def196b5a9cec932ee9";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "charm-0.1.2" = {
      name = "charm";
      packageName = "charm";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charm/-/charm-0.1.2.tgz";
        sha1 = "06c21eed1a1b06aeb67553cdc53e23274bac2296";
      };
    };
    "cli-table-0.3.1" = {
      name = "cli-table";
      packageName = "cli-table";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz";
        sha1 = "f53b05266a8b1a0b934b3d0821e6e2dc5914ae23";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "drawille-blessed-contrib-1.0.0" = {
      name = "drawille-blessed-contrib";
      packageName = "drawille-blessed-contrib";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/drawille-blessed-contrib/-/drawille-blessed-contrib-1.0.0.tgz";
        sha1 = "15c27934f57a0056ad13596e1561637bc941f0b7";
      };
    };
    "drawille-canvas-blessed-contrib-0.1.3" = {
      name = "drawille-canvas-blessed-contrib";
      packageName = "drawille-canvas-blessed-contrib";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/drawille-canvas-blessed-contrib/-/drawille-canvas-blessed-contrib-0.1.3.tgz";
        sha1 = "212f078a722bfd2ecc267ea86ab6dddc1081fd48";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-3.0.0" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.0.0.tgz";
        sha1 = "53cf247acda77313e551c3aa2e73342d3fb4f7d9";
      };
    };
    "event-stream-0.9.8" = {
      name = "event-stream";
      packageName = "event-stream";
      version = "0.9.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-stream/-/event-stream-0.9.8.tgz";
        sha1 = "5da9cf3c7900975989db5a68c28e5b3c98ebe03a";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "gl-matrix-2.4.0" = {
      name = "gl-matrix";
      packageName = "gl-matrix";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gl-matrix/-/gl-matrix-2.4.0.tgz";
        sha1 = "2089b13301a29eec822d9d99dffc1f78ee9a3c50";
      };
    };
    "har-schema-1.0.5" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-1.0.5.tgz";
        sha1 = "d263135f43307c02c602afc8fe95970c0151369e";
      };
    };
    "har-validator-4.2.1" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-4.2.1.tgz";
        sha1 = "33481d0f1bbff600dd203d75812a6a5fba002e2a";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "here-0.0.2" = {
      name = "here";
      packageName = "here";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/here/-/here-0.0.2.tgz";
        sha1 = "69c1af3f02121f3d8788e02e84dc8b3905d71195";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "lodash.toarray-4.4.0" = {
      name = "lodash.toarray";
      packageName = "lodash.toarray";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.toarray/-/lodash.toarray-4.4.0.tgz";
        sha1 = "24c4bfcd6b2fba38bfd0594db1179d8e9b656561";
      };
    };
    "map-canvas-0.1.5" = {
      name = "map-canvas";
      packageName = "map-canvas";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-canvas/-/map-canvas-0.1.5.tgz";
        sha1 = "8be6bade0bf3e9f9a8b56e8836a1d1d133cab186";
      };
    };
    "marked-0.3.6" = {
      name = "marked";
      packageName = "marked";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.3.6.tgz";
        sha1 = "b2c6c618fccece4ef86c4fc6cb8a7cbf5aeda8d7";
      };
    };
    "marked-terminal-1.7.0" = {
      name = "marked-terminal";
      packageName = "marked-terminal";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked-terminal/-/marked-terminal-1.7.0.tgz";
        sha1 = "c8c460881c772c7604b64367007ee5f77f125904";
      };
    };
    "memory-streams-0.1.2" = {
      name = "memory-streams";
      packageName = "memory-streams";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-streams/-/memory-streams-0.1.2.tgz";
        sha1 = "273ff777ab60fec599b116355255282cca2c50c2";
      };
    };
    "memorystream-0.3.1" = {
      name = "memorystream";
      packageName = "memorystream";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memorystream/-/memorystream-0.3.1.tgz";
        sha1 = "86d7090b30ce455d63fbae12dda51a47ddcaf9b2";
      };
    };
    "mime-db-1.29.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.29.0.tgz";
        sha1 = "48d26d235589651704ac5916ca06001914266878";
      };
    };
    "mime-types-2.1.16" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.16.tgz";
        sha1 = "2b858a52e5ecd516db897ac2be87487830698e23";
      };
    };
    "node-emoji-1.8.1" = {
      name = "node-emoji";
      packageName = "node-emoji";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-emoji/-/node-emoji-1.8.1.tgz";
        sha512 = "1bdm7sms59bj5fa575nda007mvn4nibjla4hm9bf9ry70kgqw7slmz3l4md4cyx2j4zda0dh0mcjildkzq7ba3i9qzapha93l14qjzs";
      };
    };
    "nopt-2.1.2" = {
      name = "nopt";
      packageName = "nopt";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-2.1.2.tgz";
        sha1 = "6cccd977b80132a07731d6e8ce58c2c8303cf9af";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "optimist-0.2.8" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.2.8.tgz";
        sha1 = "e981ab7e268b457948593b55674c099a815cac31";
      };
    };
    "optimist-0.3.7" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz";
        sha1 = "c90941ad59e4273328923074d2cf2e7cbc6ec0d9";
      };
    };
    "performance-now-0.2.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-0.2.0.tgz";
        sha1 = "33ef30c5c77d4ea21c5a53869d91b56d8f2555e5";
      };
    };
    "picture-tube-0.0.4" = {
      name = "picture-tube";
      packageName = "picture-tube";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/picture-tube/-/picture-tube-0.0.4.tgz";
        sha1 = "21de02b7179ccb73af083f112f5267632fc6e8c6";
      };
    };
    "png-js-0.1.1" = {
      name = "png-js";
      packageName = "png-js";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/png-js/-/png-js-0.1.1.tgz";
        sha1 = "1cc7c212303acabe74263ec3ac78009580242d93";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "redeyed-1.0.1" = {
      name = "redeyed";
      packageName = "redeyed";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redeyed/-/redeyed-1.0.1.tgz";
        sha1 = "e96c193b40c0816b00aec842698e61185e55498a";
      };
    };
    "request-2.81.0" = {
      name = "request";
      packageName = "request";
      version = "2.81.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.81.0.tgz";
        sha1 = "c6928946a0e06c5f8d6f8a9333469ffda46298a0";
      };
    };
    "request-2.9.203" = {
      name = "request";
      packageName = "request";
      version = "2.9.203";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.9.203.tgz";
        sha1 = "6c1711a5407fb94a114219563e44145bcbf4723a";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "1dn291mjsda42w8kldlbmngk6dhjxfbvvd5lckyqmwbjaj6069iq3wx0nvcfglwnpddz2qa93lzf4hv77iz43bd2qixa079sjzl799n";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "sparkline-0.1.2" = {
      name = "sparkline";
      packageName = "sparkline";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sparkline/-/sparkline-0.1.2.tgz";
        sha1 = "c3bde46252b1354e710c4b200d54816bd9f07a32";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "systeminformation-3.25.1" = {
      name = "systeminformation";
      packageName = "systeminformation";
      version = "3.25.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/systeminformation/-/systeminformation-3.25.1.tgz";
        sha1 = "05e211676dcf4b2778a82744a812c70290119401";
      };
    };
    "term-canvas-0.0.5" = {
      name = "term-canvas";
      packageName = "term-canvas";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/term-canvas/-/term-canvas-0.0.5.tgz";
        sha1 = "597afac2fa6369a6f17860bce9c5f66d6ea0ca96";
      };
    };
    "tough-cookie-2.3.2" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.2.tgz";
        sha1 = "f081f76e4c85720e6c37a5faced737150d84072a";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "uuid-3.1.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz";
        sha512 = "3x5mi85l1559nkb35pfksjjgiyfyqrcvmcf0nly1xjl1kb0d37jnxd6sk0b8d331waadnqbf60nfssb563x9pvnjcw87lrh976sv18c";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "x256-0.0.2" = {
      name = "x256";
      packageName = "x256";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/x256/-/x256-0.0.2.tgz";
        sha1 = "c9af18876f7a175801d564fe70ad9e8317784934";
      };
    };
    "xml2js-0.4.17" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.17.tgz";
        sha1 = "17be93eaae3f3b779359c795b419705a8817e868";
      };
    };
    "xmlbuilder-4.2.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-4.2.1.tgz";
        sha1 = "aa58a3041a066f90eaa16c2f5389ff19f3f461a5";
      };
    };
  };
  args = {
    name = "gtop";
    packageName = "gtop";
    version = "0.1.5";
    src = fetchFromGitHub {
      owner = "aksakalli";
      repo = "gtop";
      rev = "149c7fd";
      sha256 = "1j649qx5cvhhs1pv26fc4cq1haac42w9q1943xqggf7ximchiiby";
    };
    dependencies = [
      sources."abbrev-1.1.0"
      sources."ajv-4.11.8"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."ansi-term-0.0.2"
      sources."ansicolors-0.2.1"
      sources."asn1-0.2.3"
      sources."assert-plus-0.2.0"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."bcrypt-pbkdf-1.0.1"
      sources."blessed-0.1.81"
      sources."blessed-contrib-4.7.5"
      sources."boom-2.10.1"
      sources."bresenham-0.0.3"
      sources."buffers-0.1.1"
      sources."cardinal-1.0.0"
      sources."caseless-0.12.0"
      sources."chalk-1.1.3"
      sources."charm-0.1.2"
      sources."cli-table-0.3.1"
      sources."co-4.6.0"
      sources."colors-1.0.3"
      sources."combined-stream-1.0.5"
      sources."core-util-is-1.0.2"
      sources."cryptiles-2.0.5"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."delayed-stream-1.0.0"
      sources."drawille-blessed-contrib-1.0.0"
      sources."drawille-canvas-blessed-contrib-0.1.3"
      sources."ecc-jsbn-0.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-3.0.0"
      (sources."event-stream-0.9.8" // {
        dependencies = [
          sources."optimist-0.2.8"
        ];
      })
      sources."extend-3.0.1"
      sources."extsprintf-1.3.0"
      sources."forever-agent-0.6.1"
      sources."form-data-2.1.4"
      (sources."getpass-0.1.7" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."gl-matrix-2.4.0"
      sources."har-schema-1.0.5"
      sources."har-validator-4.2.1"
      sources."has-ansi-2.0.0"
      sources."hawk-3.1.3"
      sources."here-0.0.2"
      sources."hoek-2.16.3"
      sources."http-signature-1.1.1"
      sources."inherits-2.0.3"
      sources."is-typedarray-1.0.0"
      sources."isarray-0.0.1"
      sources."isstream-0.1.2"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-stable-stringify-1.0.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsonify-0.0.0"
      (sources."jsprim-1.4.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."lodash-4.17.4"
      sources."lodash.assign-4.2.0"
      sources."lodash.toarray-4.4.0"
      sources."map-canvas-0.1.5"
      sources."marked-0.3.6"
      sources."marked-terminal-1.7.0"
      sources."memory-streams-0.1.2"
      sources."memorystream-0.3.1"
      sources."mime-db-1.29.0"
      sources."mime-types-2.1.16"
      sources."node-emoji-1.8.1"
      sources."nopt-2.1.2"
      sources."oauth-sign-0.8.2"
      sources."optimist-0.3.7"
      sources."performance-now-0.2.0"
      (sources."picture-tube-0.0.4" // {
        dependencies = [
          sources."request-2.9.203"
        ];
      })
      sources."png-js-0.1.1"
      sources."punycode-1.4.1"
      sources."qs-6.4.0"
      sources."readable-stream-1.0.34"
      sources."redeyed-1.0.1"
      sources."request-2.81.0"
      sources."safe-buffer-5.1.1"
      sources."sax-1.2.4"
      sources."sntp-1.0.9"
      sources."sparkline-0.1.2"
      (sources."sshpk-1.13.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."string_decoder-0.10.31"
      sources."stringstream-0.0.5"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."systeminformation-3.25.1"
      sources."term-canvas-0.0.5"
      sources."tough-cookie-2.3.2"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."uuid-3.1.0"
      (sources."verror-1.10.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."wordwrap-0.0.3"
      sources."x256-0.0.2"
      sources."xml2js-0.4.17"
      sources."xmlbuilder-4.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "graphic top";
      homepage = "https://github.com/aksakalli/gtop#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
