# This file has been generated by node2nix 1.5.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "after-0.8.2" = {
      name = "after";
      packageName = "after";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/after/-/after-0.8.2.tgz";
        sha1 = "fedb394f9f0e02aa9768e702bda23b505fae7e1f";
      };
    };
    "argparse-1.0.9" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.9.tgz";
        sha1 = "73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86";
      };
    };
    "arraybuffer.slice-0.0.6" = {
      name = "arraybuffer.slice";
      packageName = "arraybuffer.slice";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/arraybuffer.slice/-/arraybuffer.slice-0.0.6.tgz";
        sha1 = "f33b2159f0532a3f3107a272c0ccfbd1ad2979ca";
      };
    };
    "backo2-1.0.2" = {
      name = "backo2";
      packageName = "backo2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/backo2/-/backo2-1.0.2.tgz";
        sha1 = "31ab1ac8b129363463e35b3ebb69f4dfcfba7947";
      };
    };
    "base64-arraybuffer-0.1.5" = {
      name = "base64-arraybuffer";
      packageName = "base64-arraybuffer";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-arraybuffer/-/base64-arraybuffer-0.1.5.tgz";
        sha1 = "73926771923b5a19747ad666aa5cd4bf9c6e9ce8";
      };
    };
    "base64id-1.0.0" = {
      name = "base64id";
      packageName = "base64id";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64id/-/base64id-1.0.0.tgz";
        sha1 = "47688cb99bb6804f0e06d3e763b1c32e57d8e6b6";
      };
    };
    "better-assert-1.0.2" = {
      name = "better-assert";
      packageName = "better-assert";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/better-assert/-/better-assert-1.0.2.tgz";
        sha1 = "40866b9e1b9e0b55b481894311e68faffaebc522";
      };
    };
    "blob-0.0.4" = {
      name = "blob";
      packageName = "blob";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/blob/-/blob-0.0.4.tgz";
        sha1 = "bcf13052ca54463f30f9fc7e95b9a47630a94921";
      };
    };
    "callsite-1.0.0" = {
      name = "callsite";
      packageName = "callsite";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsite/-/callsite-1.0.0.tgz";
        sha1 = "280398e5d664bd74038b6f0905153e6e8af1bc20";
      };
    };
    "component-bind-1.0.0" = {
      name = "component-bind";
      packageName = "component-bind";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-bind/-/component-bind-1.0.0.tgz";
        sha1 = "00c608ab7dcd93897c0009651b1d3a8e1e73bbd1";
      };
    };
    "component-emitter-1.1.2" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.1.2.tgz";
        sha1 = "296594f2753daa63996d2af08d15a95116c9aec3";
      };
    };
    "component-emitter-1.2.1" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.2.1.tgz";
        sha1 = "137918d6d78283f7df7a6b7c5a63e140e69425e6";
      };
    };
    "component-inherit-0.0.3" = {
      name = "component-inherit";
      packageName = "component-inherit";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-inherit/-/component-inherit-0.0.3.tgz";
        sha1 = "645fc4adf58b72b649d5cae65135619db26ff143";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "debug-2.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.3.3.tgz";
        sha1 = "40c453e67e6e13c901ddec317af8986cda9eff8c";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "engine.io-1.8.5" = {
      name = "engine.io";
      packageName = "engine.io";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io/-/engine.io-1.8.5.tgz";
        sha512 = "3ff3a0anvy48mmpay3jkzlrjvxmlclq823j8jmjfdhy48xpz1syz44bwr13zdh161x1vqzsclgwb6gvgrn9vymvq98qihrdr4hxcl4g";
      };
    };
    "engine.io-client-1.8.5" = {
      name = "engine.io-client";
      packageName = "engine.io-client";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-client/-/engine.io-client-1.8.5.tgz";
        sha512 = "1kfc2cmjw891x0i9cm9alm93db5s40h3n4a3zcpjha7nrvz0s7ggzpp2x2v8zmnhp9278amjdm0j5lfkn3qxan7nanzhl4m4wgy1101";
      };
    };
    "engine.io-parser-1.3.2" = {
      name = "engine.io-parser";
      packageName = "engine.io-parser";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-parser/-/engine.io-parser-1.3.2.tgz";
        sha1 = "937b079f0007d0893ec56d46cb220b8cb435220a";
      };
    };
    "fresh-0.2.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz";
        sha1 = "bfd9402cf3df12c4a4c310c79f99a3dde13d34a7";
      };
    };
    "has-binary-0.1.7" = {
      name = "has-binary";
      packageName = "has-binary";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-binary/-/has-binary-0.1.7.tgz";
        sha1 = "68e61eb16210c9545a0a5cce06a873912fe1e68c";
      };
    };
    "has-cors-1.1.0" = {
      name = "has-cors";
      packageName = "has-cors";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-cors/-/has-cors-1.1.0.tgz";
        sha1 = "5e474793f7ea9843d1bb99c23eef49ff126fff39";
      };
    };
    "highlight.js-8.9.1" = {
      name = "highlight.js";
      packageName = "highlight.js";
      version = "8.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/highlight.js/-/highlight.js-8.9.1.tgz";
        sha1 = "b8a9c5493212a9392f0222b649c9611497ebfb88";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "json3-3.3.2" = {
      name = "json3";
      packageName = "json3";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json3/-/json3-3.3.2.tgz";
        sha1 = "3c0434743df93e2f5c42aee7b19bcb483575f4e1";
      };
    };
    "linkify-it-0.1.5" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-0.1.5.tgz";
        sha1 = "38c583d32fa93ed726da00c7af001078bfb6b945";
      };
    };
    "markdown-it-3.1.0" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-3.1.0.tgz";
        sha1 = "20a71e8e67b1297c96ac47d00f7b6e690d6e0c36";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "mime-1.2.11" = {
      name = "mime";
      packageName = "mime";
      version = "1.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.2.11.tgz";
        sha1 = "58203eed86e3a5ef17aed2b7d9ebd47f0a60dd10";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "object-component-0.0.3" = {
      name = "object-component";
      packageName = "object-component";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-component/-/object-component-0.0.3.tgz";
        sha1 = "f0c69aa50efc95b866c186f400a33769cb2f1291";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "parsejson-0.0.3" = {
      name = "parsejson";
      packageName = "parsejson";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parsejson/-/parsejson-0.0.3.tgz";
        sha1 = "ab7e3759f209ece99437973f7d0f1f64ae0e64ab";
      };
    };
    "parseqs-0.0.5" = {
      name = "parseqs";
      packageName = "parseqs";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseqs/-/parseqs-0.0.5.tgz";
        sha1 = "d5208a3738e46766e291ba2ea173684921a8b89d";
      };
    };
    "parseuri-0.0.5" = {
      name = "parseuri";
      packageName = "parseuri";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseuri/-/parseuri-0.0.5.tgz";
        sha1 = "80204a50d4dbb779bfdc6ebe2778d90e4bce320a";
      };
    };
    "range-parser-0.0.4" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz";
        sha1 = "c0427ffef51c10acba0782a46c9602e744ff620b";
      };
    };
    "send-0.1.4" = {
      name = "send";
      packageName = "send";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.1.4.tgz";
        sha1 = "be70d8d1be01de61821af13780b50345a4f71abd";
      };
    };
    "socket.io-1.7.4" = {
      name = "socket.io";
      packageName = "socket.io";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io/-/socket.io-1.7.4.tgz";
        sha1 = "2f7ecedc3391bf2d5c73e291fe233e6e34d4dd00";
      };
    };
    "socket.io-adapter-0.5.0" = {
      name = "socket.io-adapter";
      packageName = "socket.io-adapter";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-0.5.0.tgz";
        sha1 = "cb6d4bb8bec81e1078b99677f9ced0046066bb8b";
      };
    };
    "socket.io-client-1.7.4" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-1.7.4.tgz";
        sha1 = "ec9f820356ed99ef6d357f0756d648717bdd4281";
      };
    };
    "socket.io-parser-2.3.1" = {
      name = "socket.io-parser";
      packageName = "socket.io-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.3.1.tgz";
        sha1 = "dd532025103ce429697326befd64005fcfe5b4a0";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "to-array-0.1.4" = {
      name = "to-array";
      packageName = "to-array";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-array/-/to-array-0.1.4.tgz";
        sha1 = "17e6c11f73dd4f3d74cda7a4ff3238e9ad9bf890";
      };
    };
    "uc.micro-0.1.0" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-0.1.0.tgz";
        sha1 = "eda1121d1fdb96154ed6fde8247bbbdb833308ca";
      };
    };
    "uc.micro-1.0.5" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.5.tgz";
        sha512 = "0pb6n8f5qpdf3x1bgxlcvimha0n4xx3mgr1mj6nx6yksgg9ij62ai3nzhyy8806gfkklfk8blhlhimw0237yg9xr66rmgvk1vici0i6";
      };
    };
    "ultron-1.0.2" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz";
        sha1 = "ace116ab557cd197386a4e88f4685378c8b2e4fa";
      };
    };
    "ws-1.1.5" = {
      name = "ws";
      packageName = "ws";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-1.1.5.tgz";
        sha512 = "3iv2yz706h7wyg563jsfjdykkkxs8j49vz60r6qx5by0npfhs98rgc114kdqs15sc52mldscc22bkfpkrs08cwlqaxx8lfdjn5alwm3";
      };
    };
    "wtf-8-1.0.0" = {
      name = "wtf-8";
      packageName = "wtf-8";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wtf-8/-/wtf-8-1.0.0.tgz";
        sha1 = "392d8ba2d0f1c34d1ee2d630f15d0efb68e1048a";
      };
    };
    "xmlhttprequest-ssl-1.5.3" = {
      name = "xmlhttprequest-ssl";
      packageName = "xmlhttprequest-ssl";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-1.5.3.tgz";
        sha1 = "185a888c04eca46c3e4070d99f7b49de3528992d";
      };
    };
    "yeast-0.1.2" = {
      name = "yeast";
      packageName = "yeast";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yeast/-/yeast-0.1.2.tgz";
        sha1 = "008e06d8094320c372dbc2f8ed76a0ca6c8ac419";
      };
    };
  };
  args = {
    name = "instant-markdown-d";
    packageName = "instant-markdown-d";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."highlight.js-8.9.1"
      (sources."markdown-it-3.1.0" // {
        dependencies = [
          (sources."argparse-1.0.9" // {
            dependencies = [
              sources."sprintf-js-1.0.3"
            ];
          })
          (sources."linkify-it-0.1.5" // {
            dependencies = [
              sources."uc.micro-1.0.5"
            ];
          })
          sources."mdurl-1.0.1"
          sources."uc.micro-0.1.0"
        ];
      })
      (sources."send-0.1.4" // {
        dependencies = [
          (sources."debug-3.1.0" // {
            dependencies = [
              sources."ms-2.0.0"
            ];
          })
          sources."fresh-0.2.0"
          sources."mime-1.2.11"
          sources."range-parser-0.0.4"
        ];
      })
      (sources."socket.io-1.7.4" // {
        dependencies = [
          (sources."debug-2.3.3" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          (sources."engine.io-1.8.5" // {
            dependencies = [
              (sources."accepts-1.3.3" // {
                dependencies = [
                  (sources."mime-types-2.1.17" // {
                    dependencies = [
                      sources."mime-db-1.30.0"
                    ];
                  })
                  sources."negotiator-0.6.1"
                ];
              })
              sources."base64id-1.0.0"
              sources."cookie-0.3.1"
              (sources."engine.io-parser-1.3.2" // {
                dependencies = [
                  sources."after-0.8.2"
                  sources."arraybuffer.slice-0.0.6"
                  sources."base64-arraybuffer-0.1.5"
                  sources."blob-0.0.4"
                  sources."wtf-8-1.0.0"
                ];
              })
              (sources."ws-1.1.5" // {
                dependencies = [
                  sources."options-0.0.6"
                  sources."ultron-1.0.2"
                ];
              })
            ];
          })
          (sources."has-binary-0.1.7" // {
            dependencies = [
              sources."isarray-0.0.1"
            ];
          })
          sources."object-assign-4.1.0"
          sources."socket.io-adapter-0.5.0"
          (sources."socket.io-client-1.7.4" // {
            dependencies = [
              sources."backo2-1.0.2"
              sources."component-bind-1.0.0"
              sources."component-emitter-1.2.1"
              (sources."engine.io-client-1.8.5" // {
                dependencies = [
                  sources."component-inherit-0.0.3"
                  (sources."engine.io-parser-1.3.2" // {
                    dependencies = [
                      sources."after-0.8.2"
                      sources."arraybuffer.slice-0.0.6"
                      sources."base64-arraybuffer-0.1.5"
                      sources."blob-0.0.4"
                      sources."wtf-8-1.0.0"
                    ];
                  })
                  sources."has-cors-1.1.0"
                  (sources."parsejson-0.0.3" // {
                    dependencies = [
                      (sources."better-assert-1.0.2" // {
                        dependencies = [
                          sources."callsite-1.0.0"
                        ];
                      })
                    ];
                  })
                  (sources."parseqs-0.0.5" // {
                    dependencies = [
                      (sources."better-assert-1.0.2" // {
                        dependencies = [
                          sources."callsite-1.0.0"
                        ];
                      })
                    ];
                  })
                  (sources."ws-1.1.5" // {
                    dependencies = [
                      sources."options-0.0.6"
                      sources."ultron-1.0.2"
                    ];
                  })
                  sources."xmlhttprequest-ssl-1.5.3"
                  sources."yeast-0.1.2"
                ];
              })
              sources."indexof-0.0.1"
              sources."object-component-0.0.3"
              (sources."parseuri-0.0.5" // {
                dependencies = [
                  (sources."better-assert-1.0.2" // {
                    dependencies = [
                      sources."callsite-1.0.0"
                    ];
                  })
                ];
              })
              sources."to-array-0.1.4"
            ];
          })
          (sources."socket.io-parser-2.3.1" // {
            dependencies = [
              sources."component-emitter-1.1.2"
              (sources."debug-2.2.0" // {
                dependencies = [
                  sources."ms-0.7.1"
                ];
              })
              sources."isarray-0.0.1"
              sources."json3-3.3.2"
            ];
          })
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Instantly-updating Markdown Server";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}