#!/bin/sh
#
# ufetch-nixos - tiny system info for nixos
#

## INFO

global_packages=$(nix-store -q --references /nix/var/nix/profiles/system/sw |  wc | awk '{print$1;}')
user_packages=$(nix-store -q --references /nix/var/nix/profiles/per-user/${USER}/profile | wc | awk '{print$1;}')
# user is already defined
host="$(hostname)"
os="NixOS $(nixos-version | awk '{print$2;}')"
rev="$(nix-help rev -s)" 
pkg_rev="$(nix-help rev -f nixpkgs -s)"
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="${global_packages} + ${user_packages}"
shell="$(basename ${SHELL})"
if [ -z "${WM}" ]; then
	WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
fi
resolution="$(xrandr | grep "*" | awk '{print$1;}')"
## DEFINE COLORS

# probably don't change these
bc="$(tput bold)"		# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"		# reset

# you can change these
lc="${rc}${bc}${c4}"	# labels
nc="${rc}${bc}${c4}"	# user and hostname
ic="${rc}${bc}${c7}"	# info
fc="${rc}${c4}"			# first color
sc="${rc}${bc}${c4}"	# second color

lc="${rc}${bc}${c6}"
nc="${rc}${bc}${c6}"
ic="${rc}${bc}${c7}"
pc="${rc}${c6}"

## Output
cat <<EOF

${pc}      ___     ${nc}${USER}${ic}@${nc}${host}${rc}
${pc}     (${c7}.· ${pc}|    ${lc}OS:        ${ic}${os}${rc}
${pc}     (${c3}<> ${pc}|    ${lc}REVISION:  ${ic}${rev}/${pkg_rev}${rc}
${pc}    / ${c7}__  ${pc}\\   ${lc}KERNEL:    ${ic}${kernel}${rc}
${pc}   ( ${c7}/  \\ ${pc}/|  ${lc}UPTIME:    ${ic}${uptime}${rc}
${c3}  _${pc}/\\ ${c7}__)${pc}/${c3}_${pc})  ${lc}PACKAGES:  ${ic}${packages}${rc}
${c3}  \/${pc}-____${c3}\/   ${lc}SCREEN:    ${ic}${resolution}${rc}

EOF
