# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  # Kernel version
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Use unfree Intel drivers
  hardware.enableRedistributableFirmware = true;
  
  # Default kernel modules 
  boot.initrd.availableKernelModules = [
    "xhci_pci" "nvme" "usb_storage" "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.blacklistedKernelModules = [ "i915" ];
  boot.extraModulePackages = [ ];

  # Enable basic NVIDIA support (needs testing)
  # https://github.com/NixOS/nixpkgs/issues/53269#issuecomment-454726649
  services.xserver.videoDrivers = [ "intel" ];
  hardware.bumblebee.enable = true;
  hardware.opengl.enable = true;
  hardware.opengl.driSupport32Bit = true;
  hardware.opengl.extraPackages = [
    pkgs.libGL_driver
    pkgs.linuxPackages.nvidia_x11.out
  ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Filesystem (configured by nixos-install)
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a08f78e7-bc3b-4f1c-8332-d4c098f9cb78";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D9F0-DD1D";
    fsType = "vfat";
  };
    
  swapDevices = [
    { device = "/dev/disk/by-uuid/f2c44b27-e6d3-46ea-9db6-b581f184120b"; }
  ];

  # Other defaults
  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
