# This file has been generated by node2nix 1.5.2. Do not edit!

{nodeEnv, fetchurl, fetchgit, fetchFromGitHub, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "38s4f3id97wsb0rg9nm9zvxyq0nvwrmrpa5dzvrkp36mf5ibs98b4z6lvsbrwzzs0sbcank6c7gpp06vcwp9acfhp41rzlhi3ybsxwy";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-term-0.0.2" = {
      name = "ansi-term";
      packageName = "ansi-term";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-term/-/ansi-term-0.0.2.tgz";
        sha1 = "fd753efa4beada0eac99981bc52a3f6ff019deb7";
      };
    };
    "ansicolors-0.2.1" = {
      name = "ansicolors";
      packageName = "ansicolors";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansicolors/-/ansicolors-0.2.1.tgz";
        sha1 = "be089599097b74a5c9c4a84a0cdbcdb62bd87aef";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "blessed-0.1.81" = {
      name = "blessed";
      packageName = "blessed";
      version = "0.1.81";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed/-/blessed-0.1.81.tgz";
        sha1 = "f962d687ec2c369570ae71af843256e6d0ca1129";
      };
    };
    "blessed-contrib-4.8.5" = {
      name = "blessed-contrib";
      packageName = "blessed-contrib";
      version = "4.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed-contrib/-/blessed-contrib-4.8.5.tgz";
        sha1 = "39796717c7fe3e4cb4b074cdc8ae2f9280e97ff8";
      };
    };
    "boom-4.3.1" = {
      name = "boom";
      packageName = "boom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-4.3.1.tgz";
        sha1 = "4f8a3005cb4a7e3889f749030fd25b96e01d2e31";
      };
    };
    "boom-5.2.0" = {
      name = "boom";
      packageName = "boom";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-5.2.0.tgz";
        sha512 = "19h20yqpvca08dns1rs4f057f10w63v0snxfml4h5khsk266x3x1im0w72bza4k2xn0kfz6jlv001dhcvxsjr09bmbqnysils9m7437";
      };
    };
    "bresenham-0.0.3" = {
      name = "bresenham";
      packageName = "bresenham";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bresenham/-/bresenham-0.0.3.tgz";
        sha1 = "abdab9e5b194e27c757cd314d8444314f299877a";
      };
    };
    "buffers-0.1.1" = {
      name = "buffers";
      packageName = "buffers";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz";
        sha1 = "b24579c3bed4d6d396aeee6d9a8ae7f5482ab7bb";
      };
    };
    "cardinal-1.0.0" = {
      name = "cardinal";
      packageName = "cardinal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cardinal/-/cardinal-1.0.0.tgz";
        sha1 = "50e21c1b0aa37729f9377def196b5a9cec932ee9";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "charm-0.1.2" = {
      name = "charm";
      packageName = "charm";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charm/-/charm-0.1.2.tgz";
        sha1 = "06c21eed1a1b06aeb67553cdc53e23274bac2296";
      };
    };
    "cli-table-0.3.1" = {
      name = "cli-table";
      packageName = "cli-table";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz";
        sha1 = "f53b05266a8b1a0b934b3d0821e6e2dc5914ae23";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cryptiles-3.1.2" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz";
        sha1 = "a89fbb220f5ce25ec56e8c4aa8a4fd7b5b0d29fe";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "drawille-blessed-contrib-1.0.0" = {
      name = "drawille-blessed-contrib";
      packageName = "drawille-blessed-contrib";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/drawille-blessed-contrib/-/drawille-blessed-contrib-1.0.0.tgz";
        sha1 = "15c27934f57a0056ad13596e1561637bc941f0b7";
      };
    };
    "drawille-canvas-blessed-contrib-0.1.3" = {
      name = "drawille-canvas-blessed-contrib";
      packageName = "drawille-canvas-blessed-contrib";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/drawille-canvas-blessed-contrib/-/drawille-canvas-blessed-contrib-0.1.3.tgz";
        sha1 = "212f078a722bfd2ecc267ea86ab6dddc1081fd48";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-3.0.0" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.0.0.tgz";
        sha1 = "53cf247acda77313e551c3aa2e73342d3fb4f7d9";
      };
    };
    "event-stream-0.9.8" = {
      name = "event-stream";
      packageName = "event-stream";
      version = "0.9.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/event-stream/-/event-stream-0.9.8.tgz";
        sha1 = "5da9cf3c7900975989db5a68c28e5b3c98ebe03a";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "gl-matrix-2.4.0" = {
      name = "gl-matrix";
      packageName = "gl-matrix";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gl-matrix/-/gl-matrix-2.4.0.tgz";
        sha1 = "2089b13301a29eec822d9d99dffc1f78ee9a3c50";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "hawk-6.0.2" = {
      name = "hawk";
      packageName = "hawk";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz";
        sha512 = "1nl2hjr2mnhj5jlaz8mh54z7acwz5j5idkch04qgjk78756gw5d0fjk4a2immil5ij9ijdssb9ndpryvnh2xpcbgcjv8lxybn330als";
      };
    };
    "here-0.0.2" = {
      name = "here";
      packageName = "here";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/here/-/here-0.0.2.tgz";
        sha1 = "69c1af3f02121f3d8788e02e84dc8b3905d71195";
      };
    };
    "hoek-4.2.1" = {
      name = "hoek";
      packageName = "hoek";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-4.2.1.tgz";
        sha512 = "1y8kprb3qldxqj31zai5n8dvhydsl9nn5w4rskhnbzzhldn6pm6n5lcyam3sfkb61a62d5m58k8im7z6ngwbd9cw9zp4zm4y7ckrf20";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "lodash-4.17.5" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz";
        sha512 = "11hikgyas884mz8a58vyixaahxbpdwljdw4cb6qp15xa3sfqikp2mm6wgv41jsl34nzsv1hkx9kw3nwczvas5p73whirmaz4sxggwmj";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "lodash.toarray-4.4.0" = {
      name = "lodash.toarray";
      packageName = "lodash.toarray";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.toarray/-/lodash.toarray-4.4.0.tgz";
        sha1 = "24c4bfcd6b2fba38bfd0594db1179d8e9b656561";
      };
    };
    "map-canvas-0.1.5" = {
      name = "map-canvas";
      packageName = "map-canvas";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-canvas/-/map-canvas-0.1.5.tgz";
        sha1 = "8be6bade0bf3e9f9a8b56e8836a1d1d133cab186";
      };
    };
    "marked-0.3.18" = {
      name = "marked";
      packageName = "marked";
      version = "0.3.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.3.18.tgz";
        sha512 = "13w96f14kywqpfwqjyry6sfjyfp5ynfz9x6sbq8kssganf0hyn7glr388vsycvdh2gks6ckw2rf5hykph8afn9kbydbll2zi10vdn73";
      };
    };
    "marked-terminal-1.7.0" = {
      name = "marked-terminal";
      packageName = "marked-terminal";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked-terminal/-/marked-terminal-1.7.0.tgz";
        sha1 = "c8c460881c772c7604b64367007ee5f77f125904";
      };
    };
    "memory-streams-0.1.3" = {
      name = "memory-streams";
      packageName = "memory-streams";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-streams/-/memory-streams-0.1.3.tgz";
        sha512 = "2j658v3l5i2w7vxpd8aspfixfw7c2jm8klz970k18mgzmjz80y9fsq93k37il1nzj9pcr8ipblxyfrl2sy354d67lkw5j0c7453ym59";
      };
    };
    "memorystream-0.3.1" = {
      name = "memorystream";
      packageName = "memorystream";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memorystream/-/memorystream-0.3.1.tgz";
        sha1 = "86d7090b30ce455d63fbae12dda51a47ddcaf9b2";
      };
    };
    "mime-db-1.33.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.33.0.tgz";
        sha512 = "36xnw59ik9fqym00cmwb5nyzg0l03k70cp413f7639j93wgmzk1mh0xjc7i6zz3r6k9xnwh0g5cm5a1f3y8c6plgy4qld7fm887ywh4";
      };
    };
    "mime-types-2.1.18" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.18.tgz";
        sha512 = "22krj1kw7n9z10zdyx7smcaim4bzwqsqzhspwha06q58gcrxfp93hw2cd0vk5crhq5p2dwzqlpacg32lrmp5sjzb798zdzy35mdmkwm";
      };
    };
    "node-emoji-1.8.1" = {
      name = "node-emoji";
      packageName = "node-emoji";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-emoji/-/node-emoji-1.8.1.tgz";
        sha512 = "1bdm7sms59bj5fa575nda007mvn4nibjla4hm9bf9ry70kgqw7slmz3l4md4cyx2j4zda0dh0mcjildkzq7ba3i9qzapha93l14qjzs";
      };
    };
    "nopt-2.1.2" = {
      name = "nopt";
      packageName = "nopt";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-2.1.2.tgz";
        sha1 = "6cccd977b80132a07731d6e8ce58c2c8303cf9af";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "optimist-0.2.8" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.2.8.tgz";
        sha1 = "e981ab7e268b457948593b55674c099a815cac31";
      };
    };
    "optimist-0.3.7" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz";
        sha1 = "c90941ad59e4273328923074d2cf2e7cbc6ec0d9";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "picture-tube-0.0.4" = {
      name = "picture-tube";
      packageName = "picture-tube";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/picture-tube/-/picture-tube-0.0.4.tgz";
        sha1 = "21de02b7179ccb73af083f112f5267632fc6e8c6";
      };
    };
    "png-js-0.1.1" = {
      name = "png-js";
      packageName = "png-js";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/png-js/-/png-js-0.1.1.tgz";
        sha1 = "1cc7c212303acabe74263ec3ac78009580242d93";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "3waqapyj1k4g135sgj636rmswiaixq19is1rw0rpv4qp6k7dl0a9nwy06m7yl5lbdk9p6xpwwngnggbzlzaz6rh11c86j2nvnnf273r";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "redeyed-1.0.1" = {
      name = "redeyed";
      packageName = "redeyed";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redeyed/-/redeyed-1.0.1.tgz";
        sha1 = "e96c193b40c0816b00aec842698e61185e55498a";
      };
    };
    "request-2.85.0" = {
      name = "request";
      packageName = "request";
      version = "2.85.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.85.0.tgz";
        sha512 = "2d3hg10zs5ycnr8prmiwdhacf88fl0x0bi6szs0z2r07zcbk419laixwpjp8sqapbc2ifyyih7p3r60wgr58bmcncz3pqnx523c8zph";
      };
    };
    "request-2.9.203" = {
      name = "request";
      packageName = "request";
      version = "2.9.203";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.9.203.tgz";
        sha1 = "6c1711a5407fb94a114219563e44145bcbf4723a";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "1dn291mjsda42w8kldlbmngk6dhjxfbvvd5lckyqmwbjaj6069iq3wx0nvcfglwnpddz2qa93lzf4hv77iz43bd2qixa079sjzl799n";
      };
    };
    "sntp-2.1.0" = {
      name = "sntp";
      packageName = "sntp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-2.1.0.tgz";
        sha512 = "0k2smmr24w5hb1cpql6vcgh58vzp4pmh9anf0bgz3arlsgq1mapnlq9fjqr6xs10aq1cmxaw987fwknqi62frax0fvs9bj3q3kmpg8l";
      };
    };
    "sparkline-0.1.2" = {
      name = "sparkline";
      packageName = "sparkline";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sparkline/-/sparkline-0.1.2.tgz";
        sha1 = "c3bde46252b1354e710c4b200d54816bd9f07a32";
      };
    };
    "sshpk-1.14.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.14.1.tgz";
        sha1 = "130f5975eddad963f1d56f92b9ac6c51fa9f83eb";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "systeminformation-3.37.7" = {
      name = "systeminformation";
      packageName = "systeminformation";
      version = "3.37.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/systeminformation/-/systeminformation-3.37.7.tgz";
        sha512 = "2qv6imhfbq7crp644787cbq7q7p80jw3s88gcim37fpm7nf7qn5k37p9jl16jkplx9arfl9sk5zi9n27r932808llvnyxb9sx1f9v7r";
      };
    };
    "term-canvas-0.0.5" = {
      name = "term-canvas";
      packageName = "term-canvas";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/term-canvas/-/term-canvas-0.0.5.tgz";
        sha1 = "597afac2fa6369a6f17860bce9c5f66d6ea0ca96";
      };
    };
    "tough-cookie-2.3.4" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.4.tgz";
        sha512 = "0ncm6j3cjq1f26mzjf04k9bkw1b08w53s4qa3a11c1bdj4pgnqv1422c1xs5jyy6y1psppjx52fhagq5zkjkgrcpdkxcdiry96r77jd";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "0843vl1c974n8kw5kn0kvhvhwk8y8jydr0xkwwl2963xxmkw4ingk6xj9c8m48jw2i95giglxzq5aw5v5mij9kv7fzln8pxav1cr6cd";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "x256-0.0.2" = {
      name = "x256";
      packageName = "x256";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/x256/-/x256-0.0.2.tgz";
        sha1 = "c9af18876f7a175801d564fe70ad9e8317784934";
      };
    };
    "xml2js-0.4.19" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.19.tgz";
        sha512 = "3skianymbfq4rg2v5c1vwsz2kmxfik60qa892wh6a3rydd1wrv3l4vgyr8v4wd8krdf42jbmq7blp0ksbmwm332q5yr922fj8jngiks";
      };
    };
    "xmlbuilder-9.0.7" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "9.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz";
        sha1 = "132ee63d2ec5565c557e20f4c22df9aca686b10d";
      };
    };
  };
  args = {
    name = "gtop";
    packageName = "gtop";
    version = "0.1.4";
    src = fetchFromGitHub {
      owner = "aksakalli";
      repo = "gtop";
      rev = "v0.1.4";
      sha256 = "1kw8m71w8gqfl3a1dzinj07d8fs8fkki02wh4hr3a56wi16ddgd3";
    };
    dependencies = [
      sources."blessed-0.1.81"
      (sources."blessed-contrib-4.8.5" // {
        dependencies = [
          sources."ansi-term-0.0.2"
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."ansi-styles-2.2.1"
              sources."escape-string-regexp-1.0.5"
              (sources."has-ansi-2.0.0" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              sources."supports-color-2.0.0"
            ];
          })
          (sources."drawille-canvas-blessed-contrib-0.1.3" // {
            dependencies = [
              sources."bresenham-0.0.3"
              sources."drawille-blessed-contrib-1.0.0"
              sources."gl-matrix-2.4.0"
            ];
          })
          sources."lodash-4.17.5"
          (sources."map-canvas-0.1.5" // {
            dependencies = [
              (sources."xml2js-0.4.19" // {
                dependencies = [
                  sources."sax-1.2.4"
                  sources."xmlbuilder-9.0.7"
                ];
              })
            ];
          })
          sources."marked-0.3.18"
          (sources."marked-terminal-1.7.0" // {
            dependencies = [
              (sources."cardinal-1.0.0" // {
                dependencies = [
                  sources."ansicolors-0.2.1"
                  (sources."redeyed-1.0.1" // {
                    dependencies = [
                      sources."esprima-3.0.0"
                    ];
                  })
                ];
              })
              (sources."cli-table-0.3.1" // {
                dependencies = [
                  sources."colors-1.0.3"
                ];
              })
              sources."lodash.assign-4.2.0"
              (sources."node-emoji-1.8.1" // {
                dependencies = [
                  sources."lodash.toarray-4.4.0"
                ];
              })
            ];
          })
          (sources."memory-streams-0.1.3" // {
            dependencies = [
              (sources."readable-stream-1.0.34" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."inherits-2.0.3"
                  sources."isarray-0.0.1"
                  sources."string_decoder-0.10.31"
                ];
              })
            ];
          })
          sources."memorystream-0.3.1"
          (sources."picture-tube-0.0.4" // {
            dependencies = [
              sources."buffers-0.1.1"
              sources."charm-0.1.2"
              (sources."event-stream-0.9.8" // {
                dependencies = [
                  (sources."optimist-0.2.8" // {
                    dependencies = [
                      sources."wordwrap-0.0.3"
                    ];
                  })
                ];
              })
              (sources."optimist-0.3.7" // {
                dependencies = [
                  sources."wordwrap-0.0.3"
                ];
              })
              sources."png-js-0.1.1"
              sources."request-2.9.203"
            ];
          })
          (sources."request-2.85.0" // {
            dependencies = [
              sources."aws-sign2-0.7.0"
              sources."aws4-1.6.0"
              sources."caseless-0.12.0"
              (sources."combined-stream-1.0.6" // {
                dependencies = [
                  sources."delayed-stream-1.0.0"
                ];
              })
              sources."extend-3.0.1"
              sources."forever-agent-0.6.1"
              (sources."form-data-2.3.2" // {
                dependencies = [
                  sources."asynckit-0.4.0"
                ];
              })
              (sources."har-validator-5.0.3" // {
                dependencies = [
                  (sources."ajv-5.5.2" // {
                    dependencies = [
                      sources."co-4.6.0"
                      sources."fast-deep-equal-1.1.0"
                      sources."fast-json-stable-stringify-2.0.0"
                      sources."json-schema-traverse-0.3.1"
                    ];
                  })
                  sources."har-schema-2.0.0"
                ];
              })
              (sources."hawk-6.0.2" // {
                dependencies = [
                  sources."boom-4.3.1"
                  (sources."cryptiles-3.1.2" // {
                    dependencies = [
                      sources."boom-5.2.0"
                    ];
                  })
                  sources."hoek-4.2.1"
                  sources."sntp-2.1.0"
                ];
              })
              (sources."http-signature-1.2.0" // {
                dependencies = [
                  sources."assert-plus-1.0.0"
                  (sources."jsprim-1.4.1" // {
                    dependencies = [
                      sources."extsprintf-1.3.0"
                      sources."json-schema-0.2.3"
                      (sources."verror-1.10.0" // {
                        dependencies = [
                          sources."core-util-is-1.0.2"
                        ];
                      })
                    ];
                  })
                  (sources."sshpk-1.14.1" // {
                    dependencies = [
                      sources."asn1-0.2.3"
                      sources."bcrypt-pbkdf-1.0.1"
                      sources."dashdash-1.14.1"
                      sources."ecc-jsbn-0.1.1"
                      sources."getpass-0.1.7"
                      sources."jsbn-0.1.1"
                      sources."tweetnacl-0.14.5"
                    ];
                  })
                ];
              })
              sources."is-typedarray-1.0.0"
              sources."isstream-0.1.2"
              sources."json-stringify-safe-5.0.1"
              (sources."mime-types-2.1.18" // {
                dependencies = [
                  sources."mime-db-1.33.0"
                ];
              })
              sources."oauth-sign-0.8.2"
              sources."performance-now-2.1.0"
              sources."qs-6.5.1"
              sources."safe-buffer-5.1.1"
              sources."stringstream-0.0.5"
              (sources."tough-cookie-2.3.4" // {
                dependencies = [
                  sources."punycode-1.4.1"
                ];
              })
              sources."tunnel-agent-0.6.0"
              sources."uuid-3.2.1"
            ];
          })
          (sources."sparkline-0.1.2" // {
            dependencies = [
              sources."here-0.0.2"
              (sources."nopt-2.1.2" // {
                dependencies = [
                  sources."abbrev-1.1.1"
                ];
              })
            ];
          })
          (sources."strip-ansi-3.0.1" // {
            dependencies = [
              sources."ansi-regex-2.1.1"
            ];
          })
          sources."term-canvas-0.0.5"
          sources."x256-0.0.2"
        ];
      })
      sources."systeminformation-3.37.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "graphic top";
      homepage = "https://github.com/aksakalli/gtop#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
}
