# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "chroma-unstable-${version}";
  version = "2018-06-25";
  rev = "0c0b382eca61a71c1eb4cb4dea2bc78aa4939d96";

  goPackagePath = "github.com/alecthomas/chroma";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/alecthomas/chroma";
    sha256 = "0chpzs542s366vv01bfhrajdrbhmrvc3gi8jhpw3xgz6wfkivcp4";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
