# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/alecthomas/units";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/units";
      rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
      sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl";
    };
  }
  {
    goPackagePath = "github.com/danwakefield/fnmatch";
    fetch = {
      type = "git";
      url = "https://github.com/danwakefield/fnmatch";
      rev = "cbb64ac3d964b81592e64f957ad53df015803288";
      sha256 = "0cbf511ppsa6hf59mdl7nbyn2b2n71y0bpkzbmfkdqjhanqh1lqz";
    };
  }
  {
    goPackagePath = "github.com/dlclark/regexp2";
    fetch = {
      type = "git";
      url = "https://github.com/dlclark/regexp2";
      rev = "7632a260cbaf5e7594fc1544a503456ecd0827f1";
      sha256 = "0vhp5r0ywv9p1c74fm8xzclnwx2mg9f0764b3id7a9nwh0plisx2";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "efa589957cd060542a26d2dd7832fd6a6c6c3ade";
      sha256 = "0kshi4hvm0ayrsxqxy0599iv81kryhd2fn9lwjyczpj593cq069r";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c";
      sha256 = "0zs92j2cqaw9j8qx1sdxpv3ap0rgbs0vrvi72m40mg8aa36gd39w";
    };
  }
  {
    goPackagePath = "github.com/nicksnyder/go-i18n";
    fetch = {
      type = "git";
      url = "https://github.com/nicksnyder/go-i18n";
      rev = "f6ac3d9cf0c4b6a32527779e992ebde26bd3d948";
      sha256 = "1vg25khaf7lr90xwf97bsyn873cdi1j7nxh68s80jrg2a86zw0ff";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "c01d1270ff3e442a8a57cddc1c92dc1138598194";
      sha256 = "1fjzpcjng60mc3a4b2ql5a00d5gah84wj740dabv9kq67mpg8fxy";
    };
  }
  {
    goPackagePath = "gopkg.in/alecthomas/kingpin.v3-unstable";
    fetch = {
      type = "git";
      url = "https://gopkg.in/alecthomas/kingpin.v3-unstable";
      rev = "2b154cee082ef5c544fa8ea1750b9eb6581b0040";
      sha256 = "00m63w9y494fd6ypys2qddjc521b16i0ydgzmcyndxdnm2149nka";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "5420a8b6744d3b0345ab293f6fcba19c978f1183";
      sha256 = "0dwjrs2lp2gdlscs7bsrmyc5yf6mm4fvgw71bzr9mv2qrd2q73s1";
    };
  }
]
