# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  environment.variables = {
    NIXOS_DESCRIPTIVE_HARDWARE = [ "thinkpad" ];
  };

  # Kernel modules + other
  boot.initrd.availableKernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];
  boot.extraModulePackages = [ pkgs.linuxPackages.acpi_call ];

  # Boot loader
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot";
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.efiInstallAsRemovable = false;
  boot.loader.grub.device = "nodev";

  # Filesystem (configured by nixos-install)
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7f5fb58a-3cde-49a0-b46e-c0ed577b2692";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/02E4-E9C2";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Other
  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
