#!/usr/bin/env bash
# Limit to 1/second
date=$(date +%s)
old_date=$(cat ~/.config/ncmpcpp/notify_time)

if (( old_date+1 < date )); then
	:
else
	exit
fi

echo $date > ~/.config/ncmpcpp/notify_time

# Test if actually playing song
status="$(mpc status | awk 'NR==2{print $1;}')"
if [ $status = "[playing]" ]; then
        :
else
        exit
fi

# Get fields from mpc, split by tabs.
IFS=$'\t' read album artist title length file \
  <<< "$(mpc --format="%album% \t%artist% \t%title% \t%time% \t%file%")"

# try extracting image
FILE=~/Music/"$file"
ffmpeg -y -i "$FILE" /tmp/album.jpeg &> /dev/null

# if extract successful, with picture, else without
if [ $? -eq 0 ]; then
        image=/tmp/album.jpeg
        notify-send --urgency=low --app-name=ncmpcpp \
        -i $image "Now playing:" "$album\n$artist\n$title\n\n\n\n\n\n\n - $length"
    #.........................
else
        notify-send --urgency=low --app-name=ncmpcpp \
        "Now playing:" "$album\n$artist\n$title- $length"
fi
