#!/bin/bash
if [ -z $1 ]; then
	echo "please specify at least one argument"
	exit
fi

if [ -z $2 ]; then
	TOP=$1
	BOTTOM=$1
	LEFT=$1
	RIGHT=$1
elif [ -z $4 ]; then
	TOP=$1
	BOTTOM=$1
	LEFT=$2
	RIGHT=$2
else
	TOP=$1
	BOTTOM=$2
	LEFT=$3
	RIGHT=$4
fi

BOTTOM=$[ $BOTTOM + $BAR_WIDTH + $BAR_GAP ]

bspc config top_padding 	$TOP
bspc config bottom_padding 	$BOTTOM
bspc config left_padding 	$LEFT
bspc config right_padding 	$RIGHT
#(killall polybar && polybar example &>/dev/null &)
