#!/bin/bash
OUTPUT=~/.cache/bspwm-output

bspc subscribe > $OUTPUT &
while true; do
	inotifywait $OUTPUT
	if bspc query -N -n focused.fullscreen; then
		xdo id -drs | xargs -L1 transset 0 -i
	else
		xdo id -drs | xargs -L1 transset 1 -i
	fi
	echo "" > $OUTPUT
done
