#!/bin/sh
# Taken and modified from Liferea Github
# This script can be used to automatically add 
# subscriptions to Canto. Just supply a valid
# and correctly escaped feed URL as parameter.

if [ $# -ne 1 ]; then
	echo "Wrong parameter count!"
	echo ""
	echo "Syntax: $0 <feed URL>"
	echo ""
	exit 1
fi

URL=$1

NEWURL=`echo "$URL" | sed 's/feed\:https/https/'`

canto-remote addfeed "$NEWURL"
