#!/bin/sh

G='#00AA0077'  # green
R='#EE0000FF'   # red
W='#FFFFFFCC'  # white
W2='#FFFFFF77'  # white trans
R2='#AA0000bb'  # red 2
T='#555555FF'   # verifying

I3LOCK=$(i3lock \
--insidevercolor=$W2   \
--ringvercolor=$G     \
\
--insidewrongcolor=$R2 \
--ringwrongcolor=$R   \
\
--insidecolor=$W2      \
--ringcolor=$G        \
--linecolor=$W2        \
--separatorcolor=$W   \
\
--textcolor=$R        \
--timecolor=$G        \
--datecolor=$G        \
--layoutcolor=$G      \
--keyhlcolor=$R       \
--bshlcolor=$R        \
\
--screen 0            \
--blur 3              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--veriftext=""       \
--keylayout 2 \
)

var=$(pgrep i3lock)
if [ -n ${var} ]; then $I3LOCK; fi
