#!/bin/bash
#Script to automate downloading content via ssh
HOST="pi@raspberrypi"
HOSTDIR="~/.cache/downloads"

echo "Deleting old files from remote computer"
ssh $HOST "rm $HOSTDIR/*"

ssh $HOST bash -c "'
	mkdir $HOSTDIR -p
	cd $HOSTDIR
	echo "Executing given command"
	megadl $1
	ls 
'"

echo "Transfering files from remote computer"
scp $HOST:$HOSTDIR/* ./
