#!/bin/sh
INPUTFILE=$1
TYPE=$2
rm /tmp/rmarkdown -r
mkdir /tmp/rmarkdown
READFILE="/tmp/rmarkdown/file"
#rm $READFILE

echo "library(rmarkdown);render(\'${INPUTFILE}\',\ output_dir=\'/tmp/rmarkdown\')" | xargs Rscript -e

#echo "library(rmarkdown);render(\'${INPUTFILE}\',\ output_file=\'${FILE}\',\ output_dir=\'/tmp\',\ output_format=\'${EXTNAME}\')" | xargs Rscript -e

FILE=`ls /tmp/rmarkdown | head -1`
FILEDIR="/tmp/rmarkdown/${FILE}"
echo $FILE

mv $FILEDIR $READFILE

if xdotool search vivaldi-stable &> /dev/null; then
	#echo "\nreloading browser window"
	CURR_WID=$(pfw)
	xvkbd -window vivaldi-stable -text "\Cr" &> /dev/null
	wtf $CURR_WID
else
	#echo "\nno open browser found, starting new instance"
	(vivaldi "${READFILE}" &> /dev/null &) 
fi
