#!/bin/sh
INPUTFILE=$1
TYPE=$2
EXT="${2:-pdf}"
EXTNAME="${EXT}_document"
FILE="rmarkdown.${EXT}"
FILEDIR="/tmp/${FILE}"
READFILE="/tmp/rmarkdown"

rm $READFILE
echo "library(rmarkdown);render(\'${INPUTFILE}\',\ output_file=\'${FILE}\',\ output_dir=\'/tmp\',\ output_format=\'${EXTNAME}\')" | xargs Rscript -e
mv $FILEDIR $READFILE

if xdotool search vivaldi-stable &> /dev/null; then
	#echo "\nreloading browser window"
	CURR_WID=$(pfw)
	xvkbd -window vivaldi-stable -text "\Cr" &> /dev/null
	wtf $CURR_WID
else
	#echo "\nno open browser found, starting new instance"
	(vivaldi "${READFILE}" &> /dev/null &) 
fi
