#!/bin/sh
URL=$1
FILE=~/.cache/yt-music.html
YTDL_OUT=~/.cache/ytdl_out
#KNOWN_TAGS=$(cat ~/.config/MusicTags)


echo $KNOWN_TAGS

curl $URL > $FILE

TAGS=`cat $FILE | grep -oP "(?<=name=\"keywords\" content=\").*(?=\">)"`
TAGLIST=`echo $TAGS | sed 's/,./\n/g' | sed 's/ /_/g'`
for TAG in $TAGLIST; do
	case $TAG in
		MrSuicideSheep)
			OWNER=MrSuicideSheep
			;;
		xkito|xKito)
			OWNER=xKito
			;;
	esac
done

echo Uploader: $OWNER
case $OWNER in
	MrSuicideSheep)
		TITLE=`cat $FILE | grep -oP "(?<=<title>).*?(?=</title>)" | grep -oP "(?<=-.).*?(?=.-)"`
		ARTIST=`cat $FILE | grep -oP "(?<=<title>).*?(?=</title>)" | grep -oP "^.*?(?=.-)"`
		;;
esac
echo Title: $TITLE
echo Artist: $ARTIST
echo All Tags: $TAGS

echo "Fetching music"
(youtube-dl $URL) > $YTDL_OUT
if VIDEOFILE=`cat $YTDL_OUT | grep -oP "(?<=Merging formats into \").*(?=\")"`; then
	echo "Download successful"
else
	echo "Download failed"
	exit
fi

echo "Converting to music file"
AUDIOFILE="${VIDEOFILE%.webm}.mp3"
if ffmpeg -i "${VIDEOFILE}" -vn -ab 128k -ar 44100 -y "$AUDIOFILE" &> /dev/null; then
	echo "Converting succeeded"
	rm "$VIDEOFILE"
else
	echo "Converting failed"
	rm "$VIDEOFILE"
	exit
fi

echo "WRITING D3 Tags to file"
echo $AUDIOFILE
id3v2 --song "$TITLE" "$AUDIOFILE"
id3v2 --artist "$ARTIST" "$AUDIOFILE"
#echo Writing known tags:
#
#for KNOWN_TAG in $KNOWN_TAGS; do
#	for TAG in $TAGLIST; do
#		if [[ $KNOWN_TAG == $TAG ]]; then
#			echo $TAG | sed 's/_/ /g'
#		fi
#	done
#done
